In [67]:
# Importing the library
import pandas as pd

In [68]:
# Importing the train dataset
train = pd.read_csv("D:\Technology\Meetup\Training_Set3.csv")

In [69]:
#Importing the label data set
labels = pd.read_csv("D:\Technology\Meetup\Training_Set_Label.csv")

In [70]:
#Merge the train and labels dataset into train
train = pd.merge(train,labels)

In [71]:
y = train['status_group']

In [18]:
#Working with the date format
#from datetime import date
#from functools import partial
#convert_to_date = partial(date,month=1,day=1)
#for i in range(len(train)):
    #train['construction_year'][i] = convert_to_date(train['construction_year'][i])

C:\Users\PraveenKumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [72]:
# Working with date difference from date_recorded to construction_year
from datetime import datetime
train['construction_year'] = [datetime.strptime(i, '%d-%m-%Y') for i in train['construction_year']]
train['date_recorded'] = [datetime.strptime(i, '%d-%m-%Y') for i in train['date_recorded']]
delta = [(train['date_recorded'][i] - train['construction_year'][i]) for i in range(len(train))]
delta = pd.DataFrame(delta)
delta = delta.astype('timedelta64[D]')
delta = delta.astype(int)
train['Numdays'] = delta

In [73]:
# Encoding the dependent variable
from sklearn.preprocessing import LabelEncoder
le_statusgroup = LabelEncoder()
y = le_statusgroup.fit_transform(y)

In [74]:
# Extracting the categorical features
encoding_columns = ['basin','extraction_type_class','management_group','payment_type','water_quality','quantity_group','source','waterpoint_type_group']

In [75]:
encode_training_data = train[encoding_columns]

In [78]:
encode_training_data

,basin,extraction_type_class,management_group,payment_type,water_quality,quantity_group,source,waterpoint_type_group
0,Lake Nyasa,gravity,user-group,annually,soft,enough,spring,communal standpipe
1,Lake Victoria,gravity,user-group,never pay,soft,insufficient,rainwater harvesting,communal standpipe
2,Pangani,gravity,user-group,per bucket,soft,enough,dam,communal standpipe
3,Ruvuma / Southern Coast,submersible,user-group,never pay,soft,dry,machine dbh,communal standpipe
4,Lake Victoria,gravity,other,never pay,soft,seasonal,rainwater harvesting,communal standpipe
5,Pangani,submersible,user-group,per bucket,salty,enough,other,communal standpipe
6,Internal,handpump,user-group,never pay,soft,enough,machine dbh,hand pump
7,Lake Tanganyika,handpump,user-group,unknown,milky,enough,shallow well,hand pump
8,Lake Tanganyika,handpump,user-group,never pay,salty,seasonal,machine dbh,hand pump
9,Lake Victoria,handpump,user-group,never pay,soft,enough,shallow well,hand pump
10,Wami / Ruvu,submersible,commercial,never pay,salty,enough,machine dbh,other
11,Lake Nyasa,handpump,user-group,on failure,soft,insufficient,shallow well,hand pump
12,Internal,handpump,user-group,other,soft,enough,shallow well,hand pump
13,Pangani,gravity,user-group,monthly,soft,enough,spring,communal standpipe
14,Internal,handpump,user-group,never pay,soft,enough,shallow well,hand pump
15,Lake Tanganyika,handpump,user-group,never pay,soft,enough,machine dbh,hand pump
16,Rufiji,gravity,user-group,monthly,soft,dry,river,communal standpipe
17,Rufiji,gravity,user-group,on failure,soft,dry,river,communal standpipe
18,Lake Victoria,other,user-group,never pay,milky,insufficient,spring,other
19,Lake Nyasa,gravity,user-group,annually,soft,enough,spring,communal standpipe
20,Lake Nyasa,gravity,user-group,monthly,soft,enough,spring,communal standpipe
21,Lake Victoria,handpump,user-group,unknown,unknown,unknown,shallow well,hand pump
22,Rufiji,gravity,user-group,never pay,soft,enough,river,communal standpipe
23,Pangani,gravity,user-group,monthly,soft,enough,river,communal standpipe
24,Lake Tanganyika,gravity,user-group,unknown,soft,enough,spring,improved spring
25,Pangani,gravity,user-group,unknown,soft,enough,spring,communal standpipe
26,Ruvuma / Southern Coast,handpump,user-group,monthly,soft,enough,machine dbh,hand pump
27,Lake Victoria,handpump,user-group,never pay,soft,enough,shallow well,hand pump
28,Pangani,gravity,commercial,monthly,soft,insufficient,spring,communal standpipe
29,Pangani,gravity,user-group,monthly,soft,enough,spring,communal standpipe
...,...,...,...,...,...,...,...,...
59370,Lake Tanganyika,other,unknown,monthly,unknown,unknown,unknown,other
59371,Lake Victoria,handpump,user-group,never pay,soft,enough,shallow well,hand pump
59372,Lake Tanganyika,other,commercial,per bucket,salty,insufficient,shallow well,other
59373,Lake Rukwa,handpump,user-group,annually,soft,enough,machine dbh,hand pump
59374,Lake Victoria,handpump,user-group,other,soft,enough,shallow well,hand pump
59375,Pangani,gravity,user-group,monthly,soft,enough,river,communal standpipe
59376,Internal,other,user-group,unknown,unknown,dry,shallow well,other
59377,Internal,gravity,user-group,never pay,soft,insufficient,dam,communal standpipe
59378,Rufiji,gravity,user-group,monthly,soft,enough,spring,communal standpipe
59379,Lake Victoria,gravity,user-group,never pay,soft,enough,spring,communal standpipe
59380,Lake Nyasa,gravity,user-group,annually,soft,dry,spring,communal standpipe
59381,Pangani,gravity,user-group,never pay,soft,insufficient,spring,communal standpipe
59382,Pangani,gravity,user-group,per bucket,soft,enough,spring,communal standpipe
59383,Ruvuma / Southern Coast,handpump,user-group,unknown,soft,enough,rainwater harvesting,hand pump
59384,Lake Victoria,gravity,user-group,never pay,soft,insufficient,spring,communal standpipe
59385,Lake Victoria,handpump,user-group,monthly,salty,enough,machine dbh,hand pump
59386,Lake Rukwa,handpump,user-group,never pay,soft,enough,machine dbh,hand pump
59387,Wami / Ruvu,submersible,user-group,per bucket,soft,enough,machine dbh,communal standpipe
59388,Lake Tanganyika,gravity,user-group,unknown,soft,insufficient,spring,improved spring
59389,Lake Tanganyika,handpump,user-group,never pay,soft,enough,machine dbh,hand pump
59390,Lake Tanganyika,handpump,user-group,never pay,soft,insufficient,machine dbh,hand pump
59391,Pangani,gravity,user-group,never pay,soft,enough,river,communal standpipe
59392,Lake Rukwa,gravity,user-group,never pay,soft,enough,spring,communal standpipe
59393,Internal,gravity,commercial,per bucket,soft,insufficient,dam,other
59394,Wami / Ruvu,submersible,user-group,monthly,soft,enough,machine dbh,communal standpipe
59395,Pangani,gravity,user-group,per bucket,soft,enough,spring,communal standpipe
59396,Rufiji,gravity,user-group,annually,soft,enough,river,communal standpipe
59397,Rufiji,handpump,user-group,monthly,fluoride,enough,machine dbh,hand pump
59398,Rufiji,handpump,user-group,never pay,soft,insufficient,shallow well,hand pump
59399,Wami / Ruvu,handpump,user-group,on failure,salty,enough,shallow well,hand pump

In [77]:
# Encoding the categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
encoded_training_data = encode_training_data.apply(LabelEncoder().fit_transform)
hotencoding = OneHotEncoder(categorical_features = 'all')
encode_training_data = hotencoding.fit_transform(encode_training_data).toarray()

ValueError: could not convert string to float: 'hand pump'

In [51]:
encoded_training_data

,basin,extraction_type_class,management_group,payment_type,water_quality,quantity_group,source,waterpoint_type_group
0,1,0,4,0,6,1,8,1
1,4,0,4,2,6,2,5,1
2,5,0,4,5,6,1,0,1
3,7,5,4,2,6,0,3,1
4,4,0,1,2,6,3,5,1
5,5,5,4,5,4,1,4,1
6,0,1,4,2,6,1,3,3
7,3,1,4,6,3,1,7,3
8,3,1,4,2,4,3,3,3
9,4,1,4,2,6,1,7,3
10,8,5,0,2,4,1,3,5
11,1,1,4,3,6,2,7,3
12,0,1,4,4,6,1,7,3
13,5,0,4,1,6,1,8,1
14,0,1,4,2,6,1,7,3
15,3,1,4,2,6,1,3,3
16,6,0,4,1,6,0,6,1
17,6,0,4,3,6,0,6,1
18,4,3,4,2,3,2,8,5
19,1,0,4,0,6,1,8,1
20,1,0,4,1,6,1,8,1
21,4,1,4,6,7,4,7,3
22,6,0,4,2,6,1,6,1
23,5,0,4,1,6,1,6,1
24,3,0,4,6,6,1,8,4
25,5,0,4,6,6,1,8,1
26,7,1,4,1,6,1,3,3
27,4,1,4,2,6,1,7,3
28,5,0,0,1,6,2,8,1
29,5,0,4,1,6,1,8,1
...,...,...,...,...,...,...,...,...
59370,3,3,3,1,7,4,9,5
59371,4,1,4,2,6,1,7,3
59372,3,3,0,5,4,2,7,5
59373,2,1,4,0,6,1,3,3
59374,4,1,4,4,6,1,7,3
59375,5,0,4,1,6,1,6,1
59376,0,3,4,6,7,0,7,5
59377,0,0,4,2,6,2,0,1
59378,6,0,4,1,6,1,8,1
59379,4,0,4,2,6,1,8,1
59380,1,0,4,0,6,0,8,1
59381,5,0,4,2,6,2,8,1
59382,5,0,4,5,6,1,8,1
59383,7,1,4,6,6,1,5,3
59384,4,0,4,2,6,2,8,1
59385,4,1,4,1,4,1,3,3
59386,2,1,4,2,6,1,3,3
59387,8,5,4,5,6,1,3,1
59388,3,0,4,6,6,2,8,4
59389,3,1,4,2,6,1,3,3
59390,3,1,4,2,6,2,3,3
59391,5,0,4,2,6,1,6,1
59392,2,0,4,2,6,1,8,1
59393,0,0,0,5,6,2,0,5
59394,8,5,4,1,6,1,3,1
59395,5,0,4,5,6,1,8,1
59396,6,0,4,0,6,1,6,1
59397,6,1,4,1,1,1,3,3
59398,6,1,4,2,6,2,7,3
59399,8,1,4,3,4,1,7,3

In [52]:
train[encoding_columns] = encoded_training_data[encoding_columns]

In [53]:
features = ['amount_tsh','gps_height','longitude','latitude', 'basin','region_code','population','extraction_type_class','management_group','payment_type','quantity_group','waterpoint_type_group','Numdays']
train = train[features]

In [54]:
train.head(5)

,amount_tsh,gps_height,longitude,latitude,basin,region_code,population,extraction_type_class,management_group,payment_type,quantity_group,waterpoint_type_group,Numdays
0,6000.0,1390,34.938093,-9.856322,1,11,109,0,4,0,1,1,4455
1,0.0,1399,34.698766,-2.147466,4,20,280,0,4,2,2,1,1160
2,25.0,686,37.460664,-3.821329,5,21,250,0,4,5,1,1,1516
3,0.0,263,38.486161,-11.155298,7,90,58,5,4,2,0,1,9889
4,0.0,0,31.130847,-1.825359,4,18,0,0,1,2,3,1,1289

In [55]:
train.dtypes

amount_tsh               float64
gps_height                 int64
longitude                float64
latitude                 float64
basin                      int64
region_code                int64
population                 int64
extraction_type_class      int64
management_group           int64
payment_type               int64
quantity_group             int64
waterpoint_type_group      int64
Numdays                    int32
dtype: object

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train, y, test_size = 0.30, random_state = 0)

ValueError: Found input variables with inconsistent numbers of samples: [59400, 1]

In [61]:
str(train)

'       amount_tsh  gps_height  longitude      latitude  basin  region_code  \\\n0          6000.0        1390  34.938093 -9.856322e+00      1           11   \n1             0.0        1399  34.698766 -2.147466e+00      4           20   \n2            25.0         686  37.460664 -3.821329e+00      5           21   \n3             0.0         263  38.486161 -1.115530e+01      7           90   \n4             0.0           0  31.130847 -1.825359e+00      4           18   \n5            20.0           0  39.172796 -4.765587e+00      5            4   \n6             0.0           0  33.362410 -3.766365e+00      0           17   \n7             0.0           0  32.620617 -4.226198e+00      3           17   \n8             0.0           0  32.711100 -5.146712e+00      3           14   \n9             0.0           0  30.626991 -1.257051e+00      4           18   \n10            0.0          62  39.209518 -7.034139e+00      8           60   \n11          200.0        1062  35.770258 -1.057417e+01      1           10   \n12            0.0           0  33.798106 -3.290194e+00      0           17   \n13            0.0        1368  37.092574 -3.181783e+00      5            3   \n14            0.0           0  34.364073 -3.629333e+00      0           17   \n15            0.0        1645  31.444121 -8.274962e+00      3           15   \n16          500.0        1703  34.642439 -9.106185e+00      6           11   \n17            0.0        1656  34.569266 -9.085515e+00      6           11   \n18            0.0        1162  32.920154 -1.947868e+00      4           19   \n19          500.0        1763  34.508967 -9.894412e+00      1           11   \n20          200.0        2216  34.473430 -9.594990e+00      1           11   \n21            0.0           0   0.000000 -2.000000e-08      4           17   \n22            0.0        1510  34.586901 -8.980014e+00      6           11   \n23          500.0         672  37.940029 -4.125595e+00      5            3   \n24            0.0        1645  29.747066 -4.495568e+00      3           16   \n25            0.0        1273  37.422751 -3.317536e+00      5            3   \n26          500.0         200  39.370777 -9.942532e+00      7           80   \n27            0.0           0  31.104257 -1.735361e+00      4           18   \n28            0.0        1443  37.611126 -3.263526e+00      5            3   \n29            0.0        1256  37.061688 -3.191989e+00      5            3   \n...           ...         ...        ...           ...    ...          ...   \n59370       200.0        1154  30.058731 -4.902633e+00      3           16   \n59371         0.0           0  33.586406 -3.040369e+00      4           17   \n59372         0.0           0  32.058548 -5.052101e+00      3           14   \n59373      5000.0        1137  32.125024 -6.784358e+00      2           15   \n59374         0.0           0   0.000000 -2.000000e-08      4           17   \n59375     40000.0          54  39.046942 -5.061494e+00      5            4   \n59376         0.0        1581  34.821039 -5.076258e+00      0           13   \n59377         0.0           0  33.437012 -4.423594e+00      0           14   \n59378       500.0        2101  34.620387 -9.358405e+00      6           11   \n59379         0.0           0  31.613284 -1.820226e+00      4           18   \n59380      6000.0        1439  34.942101 -9.849198e+00      1           11   \n59381         0.0           0  38.835001 -4.880204e+00      5            4   \n59382         6.0        1383  37.454759 -3.323599e+00      5            3   \n59383         0.0          11  39.626009 -1.005750e+01      7           80   \n59384         0.0           0  30.667805 -2.483710e+00      4           18   \n59385       500.0        1327  33.951681 -2.021854e+00      4           20   \n59386         0.0        1786  31.738789 -8.532013e+00      2           15   \n59387       100.0          25  39.176480 -6.957098e+00      8            7   \n59388         0.0        1414  30.692400 -3.593827e+00      3           16   \n59389         0.0         783  30.646486 -7.365418e+00      3           15   \n59390         0.0        1715  31.370848 -8.258160e+00      3           15   \n59391         0.0         540  38.044070 -4.272218e+00      5            3   \n59392         0.0           0  33.009440 -8.520888e+00      2           12   \n59393         0.0           0  33.866852 -4.287410e+00      0           14   \n59394       500.0         351  37.634053 -6.124830e+00      8            5   \n59395        10.0        1210  37.169807 -3.253847e+00      5            3   \n59396      4700.0        1212  35.249991 -9.070629e+00      6           11   \n59397         0.0           0  34.017087 -8.750434e+00      6           12   \n59398         0.0           0  35.861315 -6.378573e+00      6            1   \n59399         0.0         191  38.104048 -6.747464e+00      8            5   \n\n       population  extraction_type_class  management_group  payment_type  \\\n0             109                      0                 4             0   \n1             280                      0                 4             2   \n2             250                      0                 4             5   \n3              58                      5                 4             2   \n4               0                      0                 1             2   \n5               1                      5                 4             5   \n6               0                      1                 4             2   \n7               0                      1                 4             6   \n8               0                      1                 4             2   \n9               0                      1                 4             2   \n10            345                      5                 0             2   \n11            250                      1                 4             3   \n12              0                      1                 4             4   \n13              1                      0                 4             1   \n14              0                      1                 4             2   \n15            200                      1                 4             2   \n16             35                      0                 4             1   \n17             50                      0                 4             3   \n18           1000                      3                 4             2   \n19              1                      0                 4             0   \n20              4                      0                 4             1   \n21              0                      1                 4             6   \n22            350                      0                 4             2   \n23            210                      0                 4             1   \n24            156                      0                 4             6   \n25            140                      0                 4             6   \n26            260                      1                 4             1   \n27              0                      1                 4             2   \n28              1                      0                 0             1   \n29              1                      0                 4             1   \n...           ...                    ...               ...           ...   \n59370           1                      3                 3             1   \n59371           0                      1                 4             2   \n59372           0                      3                 0             5   \n59373          96                      1                 4             0   \n59374           0                      1                 4             4   \n59375         609                      0                 4             1   \n59376           1                      3                 4             6   \n59377           0                      0                 4             2   \n59378          36                      0                 4             1   \n59379           0                      0                 4             2   \n59380          50                      0                 4             0   \n59381         360                      0                 4             2   \n59382           1                      0                 4             5   \n59383         800                      1                 4             6   \n59384           0                      0                 4             2   \n59385         200                      1                 4             1   \n59386        1000                      1                 4             2   \n59387         100                      5                 4             5   \n59388         500                      0                 4             6   \n59389        1500                      1                 4             2   \n59390         150                      1                 4             2   \n59391         210                      0                 4             2   \n59392           0                      0                 4             2   \n59393           0                      0                 0             5   \n59394          89                      5                 4             1   \n59395         125                      0                 4             5   \n59396          56                      0                 4             0   \n59397           0                      1                 4             1   \n59398           0                      1                 4             2   \n59399         150                      1                 4             3   \n\n       quantity_group  waterpoint_type_group  Numdays  \n0                   1                      1     4455  \n1                   2                      1     1160  \n2                   1                      1     1516  \n3                   0                      1     9889  \n4                   3                      1     1289  \n5                   1                      1      801  \n6                   1                      3     1735  \n7                   1                      3     1743  \n8                   3                      3     1768  \n9                   1                      3     1310  \n10                  1                      5       50  \n11                  2                      3     9545  \n12                  1                      3     1748  \n13                  1                      1     1534  \n14                  1                      3     1754  \n15                  1                      3     7520  \n16                  0                      1    12237  \n17                  0                      1    12299  \n18                  2                      5     4585  \n19                  1                      1     6992  \n20                  1                      1     1153  \n21                  4                      3     1867  \n22                  1                      1    12329  \n23                  1                      1     1037  \n24                  1                      4     1481  \n25                  1                      1    14300  \n26                  1                      3      746  \n27                  1                      3     1287  \n28                  2                      1     4812  \n29                  1                      1     4092  \n...               ...                    ...      ...  \n59370               4                      5     1855  \n59371               1                      3     1743  \n59372               2                      5     1765  \n59373               1                      3     9161  \n59374               1                      3     1763  \n59375               1                      1     2405  \n59376               0                      5     8434  \n59377               2                      1     1757  \n59378               1                      1     1175  \n59379               1                      1     1289  \n59380               0                      1     4455  \n59381               2                      1     7014  \n59382               1                      1     2041  \n59383               1                      3     1845  \n59384               2                      1     1286  \n59385               1                      3      672  \n59386               1                      3      963  \n59387               1                      1     4819  \n59388               2                      4     6603  \n59389               1                      3      947  \n59390               2                      3     7520  \n59391               1                      1    17016  \n59392               1                      1     1200  \n59393               2                      5     1761  \n59394               1                      1     1528  \n59395               1                      1     5236  \n59396               1                      1     5605  \n59397               1                      3     1196  \n59398               2                      3     1162  \n59399               1                      3     3368  \n\n[59400 rows x 13 columns]'

In [41]:
# Fitting random_forest to the training set
from sklearn.ensemble import RandomForestClassifier as rfc
clf = rfc(n_estimators = 100, random_state = 0)
clf.fit(X_train, y_train)
y_pred= clf.predict(X_test)

In [146]:
#from xgboost import XGBClassifier
#from xgboost import plot_importance
#xgbmodel = XGBClassifier()
#xgbmodel = xgbmodel.fit(X_train, y_train)
#from matplotlib import pyplot
#plot_importance(xgbmodel)
#pyplot.show()

In [123]:
# Fitting the XGboost algorithm with tuning parameters using GridSearch CV to the training set
#from xgboost import XGBClassifier
#from sklearn.model_selection import GridSearchCV
#from sklearn.model_selection import StratifiedKFold
# grid search
#xgbmodel = XGBClassifier()
#learning_rate = [0.0001, 0.001, 0.01, 0.1, 0.2, 0.3]
#param_grid = dict(learning_rate=learning_rate)
#kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=7)
#grid_search = GridSearchCV(xgbmodel, param_grid, scoring="neg_log_loss", n_jobs=1, cv=kfold)
#grid_result = grid_search.fit(X_train, y_train)

In [42]:
from sklearn.metrics import accuracy_score

In [43]:
accuracy = accuracy_score(y_test, y_pred)

In [45]:
accuracy

0.80218855218855223

In [39]:
# Applying k-fold cross validation
#from sklearn.model_selection import cross_val_score
#from sklearn.model_selection import StratifiedKFold
#kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=0)
#accuracies = cross_val_score(estimator = clf, X = X_train, y= y_train, cv= kfold)

In [40]:
#accuracies.mean()

0.79610694204012911

In [22]:
# Importing the test data set
test = pd.read_csv('D:/Technology/Meetup/Test_Set2.csv')

In [24]:
# Working with date difference from date_recorded to construction_year
from datetime import datetime
test['construction_year'] = [datetime.strptime(i, '%d-%m-%Y') for i in test['construction_year']]
test['date_recorded'] = [datetime.strptime(i, '%d-%m-%Y') for i in test['date_recorded']]
delta = [(test['date_recorded'][i] - test['construction_year'][i]) for i in range(len(test))]
delta = pd.DataFrame(delta)
delta = delta.astype('timedelta64[D]')
delta = delta.astype(int)
test['Numdays'] = delta

In [25]:
test['Numdays'].head(5)

0     400
1    4783
2    1127
3    9518
4    4834
Name: Numdays, dtype: int32

In [4]:
#Working with the date format
#from datetime import date
#from functools import partial
#convert_to_date = partial(date,month=1,day=1)
#for i in range(len(test)):
    #test['construction_year'][i] = convert_to_date(test['construction_year'][i])

C:\Users\PraveenKumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [26]:
features = ['amount_tsh','gps_height','longitude','latitude', 'basin','region_code','population','extraction_type_class','management_group','payment_type','water_quality','quantity_group','source','waterpoint_type_group','Numdays']
test_features = test[features]
encoding_columns = ['basin','extraction_type_class','management_group','payment_type','water_quality','quantity_group','source','waterpoint_type_group']
encode_test_data = test_features[encoding_columns]

In [27]:
encoded_test_data = encode_test_data.apply(LabelEncoder().fit_transform)

In [28]:
test_features[encoding_columns] = encoded_test_data[encoding_columns]

C:\Users\PraveenKumar\Anaconda3\lib\site-packages\pandas\core\frame.py:2450: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

In [29]:
features = ['amount_tsh','gps_height','longitude','latitude', 'basin','region_code','population','extraction_type_class','management_group','payment_type','quantity_group','waterpoint_type_group','Numdays']
test_features = test_features[features]

In [30]:
test_features.dtypes

amount_tsh               float64
gps_height                 int64
longitude                float64
latitude                 float64
basin                      int64
region_code                int64
population                 int64
extraction_type_class      int64
management_group           int64
payment_type               int64
quantity_group             int64
waterpoint_type_group      int64
Numdays                    int32
dtype: object

In [31]:
y_test_pred= clf.predict(test_features)

In [32]:
y_test_pred

array([2, 0, 2, ..., 0, 0, 2], dtype=int64)

In [33]:
y_test_pred = le_statusgroup.inverse_transform(y_test_pred)

In [34]:
y_test_pred

array(['non functional', 'functional', 'non functional', ..., 'functional',
       'functional', 'non functional'], dtype=object)

In [35]:
pd.DataFrame(y_test_pred).to_csv('output_file.csv' )